/**
 * Created by huunguyen on 5/21/15.
 */

module.exports = {
    POST_STATUS_ACTIVE: 1,
    POST_STATUS_INACTIVE: 0,
    POST_STATUS_DRAFT: 2,
    USER_STATUS_ACTIVE: 1,
    USER_STATUS_INACTIVE: 0,
    LOCATION_STATUS_ACTIVE: 1,
    LOCATION_STATUS_INACTIVE: 0,
    CATEGORY_STATUS_ACTIVE: 1,
    CATEGORY_STATUS_INACTIVE: 0,
    MESSAGE_ALERT_TYPE_DELETE:1,
    MESSAGE_ALERT_TYPE_SUCCESS:2,
    POST_BY_USER: 1,
    POST_BY_STAFF: 2,
    DOMAIN_EMAIL:'@mail.dev-inspius.com',
    SUFFIX_VIRTUAL_NAME:'depot '

};